# Generated by Django 4.2.6 on 2023-10-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='This is a skill I offer')),
            ],
        ),
    ]
